# Generated by Django 5.2.1 on 2025-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_min', models.PositiveIntegerField()),
            ],
        ),
    ]
